kordis-leitstelle/kordis

- renovate.json
Change Renovate to adhere to [semantic commits](https://docs.renovatebot.com/semantic-commits/).
> chore: change Renovate to commit semantically

- package.json
We forgot to set our license in the package.json. We should be consistent, even if our package stays private (not published on npm...).
> chore: set license in package.json

- renovate.json
wrong package name, added nx to completly disable prs related to nx workspace updates
> chore: fix renovate nrwl package exclusion

- docs/architecture-decisions/adr000-template.md
- docs/architecture-decisions/adr001-add-adr-log.md
This PR adds an architecture decision log as discussed in #49. Closes #49.
> docs: add architecture decision log

- .prettierrc
- LICENSE.md
- apps/api-e2e/src/api/api.spec.ts
- apps/api-e2e/src/support/test-setup.ts
- docs/architecture-decisions/adr000-template.md
- docs/architecture-decisions/adr001-add-adr-log.md
- docs/architecture-decisions/adr002-project-naming.md
Change Prettier to always apply line width for Markdown files via [`proseWrap`](https://prettier.io/docs/en/options.html#prose-wrap). Also, use this opportunity to apply Prettier to all files.
> style: change prettier to always wrap lines

- .github/workflows/nx-migration-checker.yml
Adds a workflow that runs every day at midnight and checks if there is a new version of NX. If so, it migrates and creates a PR.
> ci: add nx migration action

- .github/workflows/ci.yml
Until [this issue](https://community.sonarsource.com/t/sonarsource-sonarcloud-github-action-failing-with-node-js-12-error/89664/2) is resolved, we have to downgrade the sonarcloud action version
> fix(ci): set explicit sonarcloud action to resolve node version issue

- libs/api/shared/tsconfig.lib.json
- libs/api/test-helpers/tsconfig.lib.json
- nx.json
Update target to `es2021` for API instead of es6 to enable the use of new features.
NestJS itself targets `es2021`.
> feat(api): target es2021

- .dockerignore
- .github/actions/build-and-deploy-api/action.yml
- .github/workflows/next-deployment.yml
- .github/workflows/preview-deployment.yml
- apps/api/Dockerfile
- apps/api/project.json
This PR extends the pipeline to build a Docker container for the `api` and push it to the GitHub container registry.
Container Registry: https://github.com/kordis-leitstelle/kordis/pkgs/container/kordis-api
Coverage > 80% and not less than the current coverage of the main branch.~~
> ci: build and push container for api

- .github/actions/build-and-deploy-spa/action.yml
We discussed that we want to include the licenses of the packages in our SPA distribution. This PR adds a build step in CI to generate a `.txt` with licenses from ALL packages of the roots `package.json`. Later on, we can just link it somewhere in the SPA. With this, we are definitely on the safe side.
> ci(spa): generate 3rd party licenses in build action

- CONTRIBUTING.md
- apps/spa/.browserslistrc
- apps/spa/src/index.html
- docs/architecture-decisions/adr008-browser-support.md
Check ADR for reasoning. NX specifies in their [docs](https://nx.dev/recipes/tips-n-tricks/browser-support), that they rely on browserlist configs. Also check Angular's [browser support](https://angular.io/guide/browser-support).
> chore(spa): support only last 2 major versions of chromium based browsers

- apps/api/Dockerfile
Sets Node environment to production during building and execution. Also installs packages via `npm ci` to ensure that we always have the same dependencies in every environment.
> chore(api): optimize Dockerfile

- apps/api/Dockerfile
Use a non-root user for the API container for security purposes.
Coverage > 80% and not less than the current coverage of the main branch.~~
> build: use non-root user for API container

- apps/spa/src/app/app.module.ts
- apps/spa/src/environments/dynamic-config.model.ts
- apps/spa/src/environments/environment.ts
- apps/spa/src/main.ts
Fixes an issue, where the environment was not changed in the app module by overwriting the environment in the main.ts before bootstrapping the application.
> fix(spa): dynamic config not available for app module imports

- .github/workflows/ci.yml
Provide the container logs to the console for failed e2e tests.
See [this GH Action run](https://github.com/kordis-leitstelle/kordis/actions/runs/8000326648/job/21849566332?pr=685#step:20:1) for the output of a failed run.
> fix: get container logs on console in e2es

- apps/spa/docker/README.md
- apps/spa/docker/nginx.conf
Currently, the CSP configurations are hard-coded into the nginx config of the spa docker image, which also consists of the reverse proxy. As we need to add some sources, such as sentry, aadb2c and so on, which are specific to our instance, it would be a better approach to loosen the configuration to the minimum and offer an approach where the config can be adjusted to the instance's needs. Thus, this PR removes the CSP and compression config. A dedicated PR will cover the necessary changes of the infrastructure in our infra repo.
> chore(spa): make csp headers optional in docker image

- libs/api/observability/src/lib/filters/sentry-exceptions.filter.spec.ts
- libs/api/observability/src/lib/filters/sentry-exceptions.filter.ts
- libs/api/observability/src/lib/sentry-observability.module.ts
This was the reason for the containers not to start. The logger was not available in the exception filter, since it gets provided later on.
> fix(api-observability): sentry exception filter logger not provided correctly

- libs/api/shared/src/lib/models/base-entity.model.ts
- libs/api/user/src/lib/core/entity/user.entity.ts
As discussed, we want to use scalar types that match the fields best. 
- Use `ID` for identity fields as this is more declarative and is [relevant for caching (depending on the implementation)](https://www.apollographql.com/docs/apollo-server/schema/schema/#scalar-types)
- Use [the `GraphQLISODateTime` from NestJS](https://docs.nestjs.com/graphql/scalars) for `Date` objects to enable automatic deserialization on the client side and improved readability.
**Note**: Currently, custom scalar types are not supported by Apollo client. Based on [this comment](https://github.com/apollographql/apollo-feature-requests/issues/368#issuecomment-1608460456) and [this](https://community.apollographql.com/t/custom-scalars-on-the-client-side/6587/3) they are planned for version 3.10 or 3.11. However, the …
> refactor(api): use native ID and DateTime scalar types

- .github/workflows/ci.yml
- tools/db/README.md
- tools/db/kordis-db.sh
As we also need to activate replicasets in our local development DB as we did on remote, we need to change the database script a bit. Before running init, please remove the existing mongodb container!
> chore: activate replicasets for transactions in dev db init script

- .prettierrc
- libs/api/shared/src/index.ts
- libs/api/shared/src/lib/kernel/service/unit-of-work.service.spec.ts
- libs/api/shared/src/lib/kernel/service/unit-of-work.service.ts
- libs/api/shared/src/lib/kernel/shared-kernel.module.ts
To run transactions, this PR introduces a unit of work service, that starts a [MongoDB transaction](https://www.mongodb.com/docs/manual/core/transactions/#transactions-api) and automatically closes the session on disposal with the new r[esource management pattern](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management). Consequently, we also need to add the parser plugin to prettier. 
You can use it as following: call `startunitOfWork()` and manage the committing and the rollbacks yourself, or as a more convenient way call asTransactions and just pass a lambda/function that includes some repository calls.
How one should implement
```
async updateSomething(
id: string,
payload: SomeDTO,
uow?: UnitOfWork | …
```
> chore(api): add unit of work service for transactions

- apps/api/project.json
- package.json
Now, you can debug the API with `npm run serve:api:debug`. In webstorm, one can start the npm script with the in-build debugger, idk how it works in vscode
> chore(api): add config to serve api for debugging

- libs/api/shared/src/lib/kernel/graphql/subscriptions/graphql-subscription.service.spec.ts
- libs/api/shared/src/lib/kernel/graphql/subscriptions/graphql-subscription.service.ts
- libs/api/user/src/lib/infra/controller/user.resolver.spec.ts
- libs/api/user/src/lib/infra/controller/user.resolver.ts
Currently, the mapping required a resolve function in subscription handlers. By moving this to the subscription service we fix this behavior. No we have to pass the name of the graphql subscription field, and the service will map it automatically.
> fix(api-shared): graphql subscription service not returning correct structure

- libs/shared/test-helpers/src/lib/test-users.test-helper.ts
This PR fixes the `Test Admin` and `Test Org Admin` both having the same username `testadmin`. Corrected the `Test Org Admin`'s username to `testorgadmin`.
> fix: username duplicate for test users

- libs/api/organization/src/lib/infra/repository/organization.respository.spec.ts
- libs/api/organization/src/lib/infra/schema/organization.schema.ts
- libs/api/shared/src/lib/models/base-document.model.ts
- libs/api/shared/src/lib/models/base-entity.model.ts
- libs/api/shared/src/lib/models/base-model.mapper-profile.ts
- libs/api/shared/src/lib/models/base.mapper-profile.ts
This PR removes the Mongoose `Document` extension from `BaseDocument` since this is [discouraged](https://mongoosejs.com/docs/6.x/docs/typescript.html#using-extends-document) by Mongoose and leads to a lot of issues especially instantiating a document class. Additionally, most Mongoose methods like `create` or `update` return an instance of the updated entity wrapped inside a `Document` class. This way, the functionality of the `Document` class still remains.
Since the current implementation of `createdAt` does not work without extending `Document` anymore, the implementation is removed. However, the functionality can be kept by adding 
```ts
@Schema({
timestamps: true,
...
})
```
to the schemas. …
> refactor: remove document extension from base document

- libs/api/deployment/src/lib/infra/controller/deployment.resolver.ts
- libs/api/deployment/src/lib/infra/deployment.module.ts
- libs/api/unit/src/index.ts
- libs/api/unit/src/lib/data-loader/alert-groups.data-loader.spec.ts
- libs/api/unit/src/lib/data-loader/alert-groups.data-loader.ts
- libs/api/unit/src/lib/data-loader/units.data-loader.spec.ts
- libs/api/unit/src/lib/data-loader/units.data-loader.ts
- libs/api/unit/src/lib/infra/unit.module.ts
As discussed, we will register the data loaders in their respective feature modules and export the register symbol, which can be reused from anywhere in the API.
> chore(api): register data loaders in feature modules

- apps/spa/project.json
- libs/spa/view/dashboard/src/lib/dashboard.component.css
Moves the import of antd css variables from the dashboard component stylesheet into the project styles, so we can use them globally without the need to import them everytime.
> chore(spa): add antd variables via project styles

- apps/api/Dockerfile
As https://github.com/nrwl/nx/issues/22386 is fixed now, we can use `npm ci`again.
> chore(api): revert use of `npm install` due to nrwl/nx/issues/22386

- tools/db/data/collection-data.model.ts
- tools/db/data/protocol-entries.data.ts
- tools/db/data/units.data.ts
This PR fixes a bug in the typings of `RescueStationMessagePayload` and corrects the test data.
> chore: fix protocol test data

- tools/db/data/protocol-entries.data.ts
The changes distribute the protocol entries among the last 7 days to enable better UI representation and avoid a bug which occurs whenever any two protocol entries are created the exact same millisecond.
> chore: distribute test protocol entries among last 7 days

- apps/spa/src/styles.css
- libs/spa/core/auth/src/lib/components/dev-login.component.ts
- libs/spa/view/auth/src/lib/auth.component.css
- libs/spa/view/dashboard/src/lib/dashboard.component.css
This PR adds a global css parameter for spacing. The spacing is set to `8px` as reasoned [here](https://t-i-show.medium.com/why-are-there-so-many-multiples-of-8-in-web-ui-design-f6bb78a49625#:~:text=Benefits%20of%20making%20margin%20a%20multiple%20of%208&text=This%20is%20the%20main%20standard,8%2C%20it%20would%20fit%20neatly.) and [here](https://stackoverflow.com/questions/69249431/why-mostly-values-are-multiples-of-8-in-android-xml).
Furthermore, this refactors the design of the dev login component.
> style: add base spacing

- apps/api/src/app/controllers/graphql-subscriptions.controller.ts
- libs/spa/core/graphql/src/lib/graphql.module.ts
- libs/spa/core/graphql/src/lib/sse-link.ts
As Browsers limit the amount of open SSE connections,  we have to use the `singleConnection` of the graphql-sse package. This only creates one connection for all subscriptions instead of one for each subscription.
> fix: creating sse connection for each gql subscribe
